### ISSUE TITLE
Signaure and Public Key Algorithms (Figure 8 and 9) 

### ISSUE THREAD

**Issue by StefanHri** [cose-wg/CBOR-certificates#74]
I noticed few things regarding figure 8 and 9 which I don't understand:

1) What is the purpose and difference between Figure 8 and 9?
2) When we use static DH authentication with EDHOC the public static DH key can be put in a certificate. Are Figures 8,9 showing the possible algorithms for static DH keys also?
3) The names in these tables are somehow inconsistent. Some begin with id (e.g. id-ecdsa-with-shake256) and some are without id (ecdsa-with-SHA256). Is this wanted?
4) I think some of these algorithms are not suitable for IoT e.g. RSA.
5) I am not familiar with all of the algorithms and I think many of the readers are also not, therefore I think it will be good to have some table showing at least the key lengths. The performance of those algorithms on constrained IoT devices needs also to be made comparable in some form.

**Comment by emanjon** [comment]
Hi,

1. X.509 (RFC5280) has different public key and signature algorithms. This follows X.509. Some Object Identifiers (OIDs) are used for both public keys and signatures, while other are restricted to one of the uses.

2. Yes, Figure 9 show all public key algorithms. When used in EDHOC with static DH authentication, then one of the following algorithms would typically be used in the certificate

```
+-------+-----------------------------------------------------------+
|     1 | Name:        EC Public Key (Weierstraß) with secp256r1    |
|       | OID:         1.2.840.10045.2.1                            |
|       | Parameters:  namedCurve = secp256r1 (1.2.840.10045.3.1.7) |
|       | DER:         30 13 06 07 2A 86 48 CE 3D 02 01 06 08 2A 86 |
|       |              48 CE 3D 03 01 07                            |
|       | Comments:    Point compressed subjectPublicKey            |
+-------+-----------------------------------------------------------+
|     2 | Name:        EC Public Key (Weierstraß) with secp384r1    |
|       | OID:         1.2.840.10045.2.1                            |
|       | Parameters:  namedCurve = secp384r1 (1.3.132.0.34)        |
|       | DER:         30 10 06 07 2A 86 48 CE 3D 02 01 06 05 2B 81 |
|       |              04 00 22                                     |
|       | Comments:    Point compressed subjectPublicKey            |
+-------+-----------------------------------------------------------+
|     8 | Name:        X25519 (Montgomery)                          |
|       | OID:         1.3.101.110                                  |
|       | Parameters:  Absent                                       |
|       | DER:         30 05 06 03 2B 65 6E                         |
|       | Comments:                                                 |
+-------+-----------------------------------------------------------+
```

3. The names used in the version you read follows the identifiers used when registering the algorithms. The inconsistencies are following X.509 and are intentional (but not wanted). The registration of OIDs is very decentralised and a bit messy. The latest version on Github completely changes the figures to make then eaasier to understand as well as better specified.

4. Yes, several of the algorithms are not suitable for constrained IoT.

5. That's a good idea. I think we could have some section where these things are discussed on a high level in an informal way.

**Comment by highlunder** [comment]
Closing after merged PR
